"""initial_schema

Revision ID: 9b8e95fecd9c
Revises: 
Create Date: 2026-04-20 10:41:48.303232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8e95fecd9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('address_detail', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='product_schema'
    )
    op.create_index(op.f('ix_product_schema_stores_id'), 'stores', ['id'], unique=False, schema='product_schema')
    op.create_index(op.f('ix_product_schema_stores_name'), 'stores', ['name'], unique=False, schema='product_schema')
    op.create_index(op.f('ix_product_schema_stores_owner_id'), 'stores', ['owner_id'], unique=False, schema='product_schema')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('discount_price', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('expiry_minutes', sa.Integer(), nullable=True),
    sa.Column('pickup_deadline', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['product_schema.stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='product_schema'
    )
    op.create_index('ix_product_active_remaining', 'products', ['is_deleted', 'remaining'], unique=False, schema='product_schema')
    op.create_index(op.f('ix_product_schema_products_category'), 'products', ['category'], unique=False, schema='product_schema')
    op.create_index(op.f('ix_product_schema_products_id'), 'products', ['id'], unique=False, schema='product_schema')
    op.create_index(op.f('ix_product_schema_products_name'), 'products', ['name'], unique=False, schema='product_schema')
    op.create_index(op.f('ix_product_schema_products_store_id'), 'products', ['store_id'], unique=False, schema='product_schema')
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['product_schema.stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='product_schema'
    )
    op.create_index(op.f('ix_product_schema_reviews_id'), 'reviews', ['id'], unique=False, schema='product_schema')
    op.create_index('ix_review_buyer_id', 'reviews', ['buyer_id'], unique=False, schema='product_schema')
    op.create_index('ix_review_store_id', 'reviews', ['store_id'], unique=False, schema='product_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_store_id', table_name='reviews', schema='product_schema')
    op.drop_index('ix_review_buyer_id', table_name='reviews', schema='product_schema')
    op.drop_index(op.f('ix_product_schema_reviews_id'), table_name='reviews', schema='product_schema')
    op.drop_table('reviews', schema='product_schema')
    op.drop_index(op.f('ix_product_schema_products_store_id'), table_name='products', schema='product_schema')
    op.drop_index(op.f('ix_product_schema_products_name'), table_name='products', schema='product_schema')
    op.drop_index(op.f('ix_product_schema_products_id'), table_name='products', schema='product_schema')
    op.drop_index(op.f('ix_product_schema_products_category'), table_name='products', schema='product_schema')
    op.drop_index('ix_product_active_remaining', table_name='products', schema='product_schema')
    op.drop_table('products', schema='product_schema')
    op.drop_index(op.f('ix_product_schema_stores_owner_id'), table_name='stores', schema='product_schema')
    op.drop_index(op.f('ix_product_schema_stores_name'), table_name='stores', schema='product_schema')
    op.drop_index(op.f('ix_product_schema_stores_id'), table_name='stores', schema='product_schema')
    op.drop_table('stores', schema='product_schema')
    # ### end Alembic commands ###
